<?php

namespace Schoolcontact\FormationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OpinionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpinionRepository extends EntityRepository
{
}
