<?php

namespace Schoolcontact\FormationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends EntityRepository
{
	public function findVilleByID($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT v FROM SchoolcontactFormationBundle:Ville v
                            WHERE v.id = '.$id)
            ->getArrayResult();
    }
}
